name: Deploy Terraform Resources

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                account: [dev, sb, game, prd]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
