name: Set up AWS SDK with Auth
description: Using OIDC AWS Credentials and login Amazon ECR

inputs:
    environment:
        description: Target environment to deploy.
        required: true

runs:
    using: 'composite'
    steps:
        - name: OIDC AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
              aws-region: 'us-west-2'
              role-to-assume: ${{ fromJSON(env.aws_credentials_role)[inputs.environment] }}
              audience: sts.amazonaws.com
          env:
              aws_credentials_role: |
                  {
                    "dev": "arn:aws:iam::340258365836:role/oidc-github-actions-dev-role",
                    "sb": "arn:aws:iam::309217545237:role/oidc-github-actions-sb-role",
                    "game": "arn:aws:iam::340258365836:role/oidc-github-actions-dev-role",
                    "prd": "arn:aws:iam::045372454064:role/oidc-github-actions-prd-role"
                  }
        - name: login Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: Echo ECR Registry
          run: echo ${{ steps.login-ecr.outputs.registry }}
          shell: bash
        - name: Configure AWS CLI Profile
          run: |
              aws configure set profile.${{ inputs.environment }}.region us-west-2
              aws configure set profile.${{ inputs.environment }}.output json
              aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          shell: bash
