name: Set up AWS SDK with Auth
description: Using OIDC AWS Credentials and login Amazon ECR

inputs:
    AWS_ACCOUNT_ID:
        description: Target AWS_ACCOUNT_ID to deploy.
        required: true

runs:
    using: 'composite'
    steps:
        - name: OIDC AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1-node16
          with:
              aws-region: 'us-west-2'
              role-to-assume: arn:aws:iam::340258365836:role/oidc-github-actions-dev-role
                  {
                    "dev": "arn:aws:iam::340258365836:role/oidc-github-actions-dev-role",
                    "sb": "arn:aws:iam::309217545237:role/oidc-github-actions-sb-role",
                    "game": "arn:aws:iam::340258365836:role/oidc-github-actions-dev-role",
                    "prd": "arn:aws:iam::045372454064:role/oidc-github-actions-prd-role"
                  }
