name: Set up AWS SDK with Auth
description: Using OIDC AWS Credentials and login Amazon ECR

inputs:
    AWS_ACCOUNT_ID:
        description: Target AWS_ACCOUNT_ID to deploy.
        required: true

runs:
    using: 'composite'
    steps:
        - name: OIDC AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1-node16
          with:
              aws-region: 'us-west-2'
              role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/oidc-github-actions-dev-role
