name: Deploy Updated Lambda Functions

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                account: [dev, sb, game, prd]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Lambda function
              run: |
                  cd src/
                  zip -r ../lambda_function.zip updated_handler.ts
                  cd ..

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume:
                      ${{ matrix.account == 'dev' && 'arn:aws:iam::340258365836:role/oidc-github-actions-dev-role' ||
                      matrix.account == 'sb' && 'arn:aws:iam::309217545237:role/oidc-github-actions-sb-role' ||
                      matrix.account == 'game' && 'arn:aws:iam::340258365836:role/oidc-github-actions-dev-role' ||
                      matrix.account == 'prd' && 'arn:aws:iam::045372454064:role/oidc-github-actions-prd-role' }}
                  aws-region: us-east-1

            - name: Check if Lambda function exists
              id: check-lambda
              run: |
                  aws lambda get-function --function-name ${{ matrix.account == 'dev' && 'updated_crawl_data_dev_function' ||
                    matrix.account == 'sb' && 'updated_crawl_data_sb_function' ||
                    matrix.account == 'game' && 'updated_crawl_data_game_function' ||
                    matrix.account == 'prd' && 'updated_crawl_data_prd_function' }} || echo "Function does not exist"
              continue-on-error: true

            - name: Deploy Lambda Function to each account
              uses: aws-actions/aws-lambda-deploy@v1
              with:
                  function-name: ${{ matrix.account == 'dev' && 'updated_crawl_data_dev_function' ||
                      matrix.account == 'sb' && 'updated_crawl_data_sb_function' ||
                      matrix.account == 'game' && 'updated_crawl_data_game_function' ||
                      matrix.account == 'prd' && 'updated_crawl_data_prd_function' }}
                  zip-file: ./lambda_function.zip
                  role: ${{ matrix.account == 'dev' && 'arn:aws:iam::340258365836:role/oidc-github-actions-dev-role' ||
                      matrix.account == 'sb' && 'arn:aws:iam::309217545237:role/oidc-github-actions-sb-role' ||
                      matrix.account == 'game' && 'arn:aws:iam::340258365836:role/oidc-github-actions-dev-role' ||
                      matrix.account == 'prd' && 'arn:aws:iam::045372454064:role/oidc-github-actions-prd-role' }}
