name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      function:
        description: "Infra to deploy"
        required: true
        default: "crawler"
        type: choice
        options:
          - "crawler"
          - "updated-function"

      action:
        description: "Infra to deploy"
        required: true
        default: "plan"
        type: choice
        options:
          - "plan"
          - "apply"

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                account: [dev, sb, game, prd]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform Init
              run: terraform init
              working-directory: terraform/
              env:
                TF_API_KEY: ${{ secrets.TF_API_KEY }}

            - name: Terraform Plan or Apply
              run: terraform ${{ github.event.inputs.action == 'plan' && 'plan' || 'apply -auto-approve' }}
              working-directory: terraform/
              env:
                TF_API_KEY: ${{ secrets.TF_API_KEY }}
