name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      function:
        description: "Infra to deploy"
        required: true
        default: "crawler"
        type: choice
        options:
          - "crawler"
          - "updated-function"

      action:
        description: "Infra to deploy"
        required: true
        default: "plan"
        type: choice
        options:
          - "plan"
          - "apply"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

          - name: Set up Cloud SDK with Auth
            uses: ./.github/actions/setup-auth-aws
            id: setup-aws-with-auth

          - name: Terraform Init
            working-directory: terraform/
            run: terraform init

          - name: Terraform Validate
            working-directory: terraform/
            id: validate
            run: terraform validate -no-color

          - name: Terraform Plan or Apply
            env:
              FREECASH_SESSION_ID: ${{ secrets.FREECASH_SESSION_ID }}
            run: terraform ${{ github.event.inputs.action == 'plan' && 'plan' || 'apply -auto-approve' }} -var="freecash_session_id=${{ secrets.FREECASH_SESSION_ID }}"
            working-directory: terraform/
